### ISSUE TITLE
Faire que la camera peut suivre le joueur et a des limites

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#131]

**Comment by msfredb7** [comment]
Idée comme ça: On pourrait s'inspirer de la camera de Civ un peu. Si j'applique leur désign à notre jeu, ça ressemblerais à
- La camera peut être en mode 'follow' ou 'free'
- Quand ça devient ton tour, la camera se met automatiquement en mode 'follow' et se centre sur ton pawn
- Dès que le joueur input WASD ou les flêche, la camera redeviens en mode 'free'
