### ISSUE TITLE
Modifié le système de spell targeting: pouvoir target une entité au lieu d'une tuile

### ISSUE THREAD

**Issue by msfredb7** [CCC-Development/DoodleMyNoodle#135]
En ce moment, quand on target un ennemie avec une GameAction, on target en fait la tuile en dessous. Le point négatif de cette approche, c'est que si l'entité change de tuile par le moment où l'input arrive, la game action rate. E.g. Mon ami tire une flêche, j'utilise mon spell "Swap" pour échangé de place avec la flêche. Du au lag, c'est à peut prêt impossible à réussir parce que la flêche change de tuile trop vite.

Ça serait pratique de supporter "GameActionParameterEntity" au lieu de juste "GameActionParameterTile"

**Comment by msfredb7** [comment]
Nécessite l'implémentation de #134

**Comment by alex534488** [comment]
En même temps de faire cette feature, il serait intéressant de rajouter un setting d'item permettant d'énumérer une liste de component Data que l'entité doit avoir pour pouvoir être Target. Si on veut aller encore plus loin, on pourrait se construire un concept de "Entity Requirements" qui contient plein de conditions diverse à évaluer sur une entity (ex : component data de Health, sa valeur est inférieur à 2 ? -> Low health targeting).
