### ISSUE TITLE
Permettre de passer à un autre niveau après avoir complété celui dans lequel on est

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#201]
À la fin du niveau, on devrait avoir une porte, quand on interagit avec une porte on arrive dans le prochain niveau

Suggestion : 

1. Intéraction avec une porte
2. Le joueur se retrouve dans la salle préparatoire du prochain niveau
3. La salle contient 4 pistons "Ready to start"
4. Une fois que tous les joueurs sont sur les pistons, ils ont téléporté dans le niveau pour commencer

N.B. Des joueurs peuvent continuer d'être dans le niveau précédent tant qu'ils n'ont pas franchis la porte. Une fois la porte franchis il n'y a pu de retour en arrière. De toute façon pour commencer le prochain niveau il faut être tous sur les pistons.

À faire : 
- Système de player spawn adapté
- Porte interactive qui mène au prochain niveau
- Être capable de load le prochain niveau
- Être capable d'unload le niveau précédent quand tous les joueurs ont franchis la porte
- Avoir deux niveaux en même temps

**Comment by msfredb7** [comment]
supporté le changement de scène c'est pas trivial malheureusement. Ya quelques raison:
- Loader une scène c'est async et chaque joueur a un PC qui load à une vitesse différente. Il faut donc mettre le jeu sur pause en attendant que tout le monde a fini le load
- Quand on build le jeu, l'ordre des gameobjects n'est pas garantie dans la scène. Les 'ConvertToEntity(..)' ne se font donc pas appelé dans le même ordre et les joueurs vont obtenir un niveau différent dans la simulation (crée une divergence). Pour réglé ça, il va probablement falloir tackle le problème avec des "SubScene". Une subscene, c'est une scène Unity, mais qui est préconvertie en Entity. Bref le ConvertToEntity se fait dans l'éditeur quand tu save ton level. Donc tout le monde se ramasse avec le même résultat
- Quand on change de level, on doit être capable d'identifier tous les Entity qui appartenait au niveau précédent et les deletes (e.g. Il ne faudrait pas delete les joueurs). En ce moment on a rien pour ça.

**Comment by alex534488** [comment]
Pour l'instant, chaque partie est individuel, une fois la partie terminé le personnage se repose et peut ensuite passer à la prochaine aventure. Pour l'instant, une aventure peut être une gigantesque map. Éventuellement, on pourrait diviser le tout en "room" et passer d'un niveau à l'autre.

**Comment by alex534488** [comment]
Le plan pour l'instant est justement d'avoir une grosse map diviser en room et on se téléporte de l'une à l'autre. Pas besoin de load une prochaine map avant très très longtemps, ou même jamais...
