### ISSUE TITLE
Faire de nouveaux mini-games polished

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#207]
Fable 2
https://www.youtube.com/watch?v=MP9UvblRPL0
https://www.youtube.com/watch?v=JL8FKy6mzXA
https://www.youtube.com/watch?v=2YYArGhO3_E
https://www.youtube.com/watch?v=3Z4XVqJDd2I
https://www.youtube.com/watch?v=Pd7J0_Q5EQs&t=8s
https://www.youtube.com/watch?v=xyFSX7YupSk
https://www.youtube.com/watch?v=YeT4KGYq920

Super Mario Paper
https://youtu.be/oWFyHwEoN6A?t=220

Fortnite
https://youtu.be/PCw1MAU21EQ?t=47

OSU
https://www.youtube.com/watch?v=atO7fCjw0pQ

Mario Striker
https://youtu.be/Gtop2j38Qfk?t=175
https://youtu.be/Gtop2j38Qfk?t=133

Worms
https://www.youtube.com/watch?v=j4dgVcg2P2o

Lock Picking
https://www.youtube.com/watch?v=hTF3DiU-6zE

Undertale
https://www.youtube.com/watch?v=Vr4IYjeplJA

Among Us
https://www.youtube.com/watch?v=DTMOyxA6eEA

**Comment by msfredb7** [comment]
TODO:
- text explicatif dans le haut de l'écran
- cacher le HUD
- ZoneBar - CritZone pour les melee attacks
