### ISSUE TITLE
Améliorer la création des items pour que ce soit plus facile et plus simple

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#228]

**Comment by msfredb7** [comment]
problèmes:
- il est possible de fournir le mauvais data au GA
- C'est pas clair c'est quoi le data requis pour une GA
- faire des settings custom pour une GA est: long, pas clair, pas explicite
- c'est pas clair/rapide de faire l'"items visual info"
- nos items sont fragmenté dans les chunks ECS
- interactible (ingrédients) sont bizarre

idées:
- choix du GA type: drive les infos qui sont displayed en authoring
- 1 seul authoring component dynamique
- delete les components non essentiel

common components:
    - stackable
        - max stacks
    - AP Cost
    - HP Cost
    - Cooldown
    
    view:
    - anim
    - description
    - SFX
    - Survey
    - Icon
    - Name
    - Rarity
