### ISSUE TITLE
Neutral NPC

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#273]
- [ ] Quelqu'un a qui on peut parler 
- [ ] Un NPC qui nous ouvre un menu UI (ex: magasin, dialogue, etc.)
- [ ] NPC neutre qui peut devenir un AI ennemi

**Comment by msfredb7** [comment]
bougé dans: https://github.com/CCC-Development/DoodleMyNoodle/wiki/Game-Ideas
