### ISSUE TITLE
Action Inspect pour avoir plus d'informations sur son environnement

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#274]
Un peu comme dans les vieux jeux, avoir un item ou une action dans le HUD qui est une loupe, lorsque sélectionner des éléments visible à l'écran seront "highlight", si on clique sur ceux ci un bulle apparait et nous donne des informations sur l'élément en question.

**Comment by msfredb7** [comment]
bougé dans: https://github.com/CCC-Development/DoodleMyNoodle/wiki/Game-Ideas
