### ISSUE TITLE
Supporter des tuiles en diagonal

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#314]
Collision des tuiles en diagonal dans les 4 directions et regarder pour avoir des tuiles en diagonale dans la présentation également.

**Comment by alex534488** [comment]
On doit supporter de marcher sur ces tuiles, en se moment on a des problèmes avec le mouvement à cause qu'il est gauche droite et ne se fit pas sur les normales du terrain.

**Comment by msfredb7** [comment]
J'ai soumis une partie de la job, mais c'est loin d'être pleinement fonctionnel:
- Les polygon colliders ne fonctionne pas, faudrait investiguer l'issue dans Fix2D
- Les AIs et le pathfinding ne serait pas capable de travailler avec les tuiles diagonal sans un rework
