### ISSUE TITLE
La collision reste active même après la mort

### ISSUE THREAD

**Issue by msfredb7** [CCC-Development/DoodleMyNoodle#331]
![](https://cdn.discordapp.com/attachments/917241947968667688/930872466891501578/unknown.png)

**Comment by alex534488** [comment]
`        Entities
            .WithReadOnly(tileWorld)
            .WithoutBurst()
            .WithChangeFilter<NavAgentFootingState>()
            .ForEach((ref PhysicsColliderBlob collider, in NavAgentFootingState footing, in NavAgentColliderRefs colliderRefs) =>
            {
                collider.Collider = footing.Value == NavAgentFooting.AirControl
                    ? colliderRefs.AirControlCollider
                    : colliderRefs.NormalCollider;
            }).Run();`

Ligne 80 UpdateNavAgentFootingSystem

mettre collider.collider à null ou default devrait régler le problème

**Comment by alex534488** [comment]
Faudrait peut être enlever le .WithChangeFilter<NavAgentFootingState>()

**Comment by alex534488** [comment]
.WithChangeFilter() ajouté la classe Health
