### ISSUE TITLE
Utiliser ALT+TAB ouvre le prompt des tooltips et le laisse ouvert

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#34]
### **Description**
Quand on est en train d'utiliser Unity, si on fait soudainement ALT+TAB pour sortir de Unity, il est possible qu'à notre retour dans le logiciel, le pop-up des tooltips dans l'onglet projet reste coincé la. Ca nous empêche donc d'utiliser cet onglet de manière approprié.

### **Étapes pour reproduire**
1. Ouvrir Unity
2. Faire ALT+TAB pour sortir de Unity
3. Revenir dans Unity

### **Solution de contournement**
1. Cliquer dans le pop-up comme pour modifier le tooltip
2. Cliquer ailleur pour que ce dernier se ferme automatiquement

### **Exemples**
TODO

**Comment by msfredb7** [comment]
J'ferme l'issue parce qu'on a disable le tool pour l'instant
