### ISSUE TITLE
Ouvrir le projet ne fonctionne pas car on est coincé dans le chargement

### ISSUE THREAD

**Issue by alex534488** [CCC-Development/DoodleMyNoodle#35]
### **Description**
Après avoir téléchargé la dernière version du projet, il est possible d'être de pris de manière définitive dans le chargement. On reste coincé lorsqu'un fichier relié au ViewBinding est en train d'être traité.

### **Étapes pour reproduire**
1. Télécharger la dernière version
2. Ouvrir Unity
3. On peut maintenant voir qu'on reste coincé

### **Solution de contournement**
1. Arrêter complètement Unity
2. L'ouvrir à nouveau

### **Exemples**
TODO

**Comment by msfredb7** [comment]
Les tentatives de fix on fonctionné. Solution: ne pas marquer un asset Dirty sans faire AssetDatabase.Save() après
